### ISSUE TITLE
Seeing anti-extension video before movie

### ISSUE THREAD

**Issue by AugustusZ** [AugustusZ/Dnvod-Ad-Remover#14]
<img width="626" alt="screen shot 2017-08-17 at 11 46 30 pm" src="https://user-images.githubusercontent.com/8922602/29447378-77c8f674-83a6-11e7-9809-dc6f44e99b2b.png">

    <video controls="controls" 
        src="http://server1.dnvod.tv/live/404.mp4" 
        id="ckplayer_a1" width="860" height="483" autoplay="autoplay" poster="/images/logo-group.jpg" 
        style="width: 1240px; height: 697px;"></video>

But after that, it becomes to the **actual movie video**:

    <video controls="controls" 
        src="..." 
        id="ckplayer_a1" width="860" height="483" poster="/images/logo-group.jpg" 
        style="width: 1240px; height: 697px;"></video>

Should observe the attribute mutation using [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) and then autoplay the **actual movie video**.

**Comment by AugustusZ** [comment]
See #5 (solved)

**Comment by applecool** [comment]
Great job! 🐼
