### ISSUE TITLE
Here's how to fetch pending video url

### ISSUE THREAD

**Issue by Ziyu-Cheng** [AugustusZ/Dnvod-Ad-Remover#15]
`_vp["pendingVideo"][0].substring(0, _vp["pendingVideo"][0].length - "->video/mp4".length)`
Above is where the pending video url stored. Since they added "->video/mp4" after the url, we should cut this part off.
I believe we need to wait for `_vp` initialized before fetching the URL, that is when the ad in player starts playing.

**Comment by AugustusZ** [comment]
But it seems that `_vp` is a local variable declared in `http://static.dnvod.tv/js/2016/playerselection-1.2.7.52.js` which is not accessible globally (or from other scripts). 

However, it is accessible as `window._vp`.

**Comment by applecool** [comment]
Solved using the [injection method](https://stackoverflow.com/questions/46210011/cant-access-the-window-level-variable-even-though-it-exists-returns-undefined ) and got the access of the variable and replaced it with the `lastIndexOf()`:

```
var str = window['_vp']['pendingVideo'][0];
var videoUrl = str.slice(0, str.lastIndexOf('->'));
```

**Comment by Ziyu-Cheng** [comment]
Great Harsha，well done!
