### ISSUE TITLE
The plugin doesn't work anymore (1/12/2017)

### ISSUE THREAD

**Issue by MikeChongCan** [AugustusZ/Dnvod-Ad-Remover#27]
As it shown in the picture below, the plugin seems not working anymore. Could you please fix it?

![image](https://user-images.githubusercontent.com/2396817/33498783-9be9db82-d6ca-11e7-9811-6d65e5ad08e9.png)

**Comment by AugustusZ** [comment]
@imWildCat thanks for ticketing this issue. Let me see what I can do before new year comes...

**Comment by MikeChongCan** [comment]
If you don't mind, we could work together, dropping me an email about your telegram or even wechat.

In addition, sorry for my carelessness, the screen above is captured when flash is turned on. Here is the screenshot after blocking flash:
![image](https://user-images.githubusercontent.com/2396817/33499083-67675f14-d6cb-11e7-8230-0c7b6387b3bc.png)

Thanks.

**Comment by AugustusZ** [comment]
@imWildCat Just invited you for this repo, if you don't mind 😃

**Comment by MikeChongCan** [comment]
Cheers 🎉！

**Comment by MikeChongCan** [comment]
I have read part of your code and found that `window[vars[0]][vars[1]]` does not exist anymore.

In addition, I found a variable like vector which could be used for encryption (computing the signature):
![snipaste_20171204_193225](https://user-images.githubusercontent.com/2396817/33572102-de37517a-d929-11e7-8835-296177641ffd.png)

Is there any way for reverse-engineering about the js source code (http://static.dnvod.tv/js/2016/playerselection-1.2.7.81.js) ?

**Comment by AugustusZ** [comment]
It seems like they really did their job... 
Here is what i can find for decoding (may not be really helpful): http://ddecode.com/hexdecoder/
The decoded code is still tricky to understand

**Comment by MikeChongCan** [comment]
Many thanks!

**Comment by AugustusZ** [comment]
One thing to mention: the whole idea behind this extension is that, while users blocking Flash in browser, the Flash player is falling back on HTML5 video player, so that all the DOM manipulations (e.g. removing ads div) are possible. 

But it seems like, the site was refactored and the HTML5 player fallback is no longer there. This means, we have to to tackle the `flashvars` (or something like this which I have no idea about) if we still want to do it: 

```
<embed allowscriptaccess="always" allowfullscreen="true" quality="high" bgcolor="#FFF" wmode="transparent" src="/_player/954684338/ckplayer.swf" 
  flashvars="
  f=rtmp://s6-r1.dnvod.tv/live/mp4:dz-yldjqbgy11-1-02AD1BCE5.mp4&amp;loaded=loadedHandler&amp;s=0&amp;b=0&amp;c=0&amp;a=&amp;i=
  //...
  //m.dnvod.tv/cmV2x/201711241858205801160.jpg&amp;p=1&amp;h=4&amp;mobile=[object Object]" 
width="100%" height="100%" name="ckplayer_a1" id="ckplayer_a1" align="middle" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
```

Do you have any experience dealing with this? @imWildCat

**Comment by GreatYYX** [comment]
@AugustusZ Thanks for your great plugin. I made a new dnvod-ad-killer, I also noted my idea in blog. Feel free to modify it to chrome extension, contact me if you need help. https://github.com/GreatYYX/dnvod-ad-killer
