### ISSUE TITLE
Should show the whole button of fullscreening

### ISSUE THREAD

**Issue by AugustusZ** [AugustusZ/Dnvod-Ad-Remover#4]
<img width="50" alt="screen shot 2017-07-19 at 7 17 59 pm" src="https://user-images.githubusercontent.com/8922602/28397573-44d79712-6cb7-11e7-8667-ec56ad63bb1b.png">

**Comment by AugustusZ** [comment]
It just happens and I don't know how...

**Comment by applecool** [comment]
Closing this issue for now!

**Comment by AugustusZ** [comment]
Fixed by overriding `static.dnvod.tv/css/videofix-1.0.1.css` in which

```
video::-internal-media-controls-download-button {
    display: none;
}

video::-webkit-media-controls-enclosure {
    overflow: hidden;
}

video::-webkit-media-controls-panel {
    width: calc(100% + 50px);
}
```

with 

```
video#video::-internal-media-controls-download-button {
  display: initial !important;
}

video#video::-webkit-media-controls-enclosure {
  overflow: visible !important;
}

video::-webkit-media-controls-panel {
  width: 1240px !important;
}
```

See 

- [In Chrome 55, prevent showing Download button for HTML 5 video](https://stackoverflow.com/questions/41115801/in-chrome-55-prevent-showing-download-button-for-html-5-video)
- [Disable download button for Google Chrome?](https://stackoverflow.com/questions/39602852/disable-download-button-for-google-chrome/40975859#40975859)
